# Generated by Django 5.1.7 on 2025-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
