# Generated by Django 5.1.7 on 2025-03-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_info_url'),
    ]

    operations = [
    ]
