# Generated by Django 5.1.7 on 2025-03-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20250311_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='info_url',
        ),
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(),
        ),
    ]
